name: exam_shadule_new
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # Dependencies copied from old app
  device_apps: ^2.2.0
  flutter_image_compress: ^2.4.0
  image_picker: ^1.1.2
  local_auth: ^2.3.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.3
  shared_preferences: ^2.3.2
  sqflite: ^2.4.1

  get: any
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: any
  http_parser: any
  image: any
  intl: any
  path: any
  flutter_local_notifications: ^22.0.1
  connectivity_plus: ^7.2.0
  socket_io_client: ^2.0.3+1
  file_picker: ^12.0.0
  cunning_document_scanner: ^3.0.1
  pdf: ^3.12.0
  flutter_pdfview: ^1.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app_logo.png"

